### ISSUE TITLE
Please add arm support

### ISSUE THREAD

**Issue by dudu7731** [Dattel/homeassistant-influxdb2#3]
Hi, 

it would be nice to add arm support (at least 64 bit)

Thanks !

**Comment by Dattel** [comment]
hi... 
i hopefully could provide support for armhf architecture - would that be sufficient?

see here the the precompiled base image i'm using:
https://github.com/orgs/hassio-addons/packages?repo_name=addon-debian-base

the problem is, that i can't test it here with any device so i would need feedback for every build "experiment"

**Comment by dudu7731** [comment]
It's for an odroid N2+ so arm64 would be better after if you could do both it will affect more people

**Comment by dudu7731** [comment]
after i can test, no problem (after my vm to odroid migration)

**Comment by Dattel** [comment]
`Build arch value must be one of ['aarch64', 'amd64', 'armhf', 'armv7', 'i386']`

so i can only add armhf support and link to arm64 packages for building the docker.. maybe that already does the trick..
Please give it a try.

**Comment by dudu7731** [comment]
Ok i'll give a try when i'll receive my new device

**Comment by Dattel** [comment]
Works for me fine on RaspberryPi4 with HomeAssistant OS

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: InfluxDB2
 Scalable datastore for metrics, events, and real-time analytics. Running InfluxDB v2.x on ARCH64 and ARM64 Achitecture
-----------------------------------------------------------
 Add-on version: 0.0.7
 You are running the latest version of this add-on.
```

**Comment by dudu7731** [comment]
Just installed it on my odroid, all is fine, thanks a lot for your work

**Comment by Dattel** [comment]
Please remember, that my attempt to provide influxdb2 is an early implementation.
I'm neither an influx expert nor an homeassistant selfcreated-addon-experienced user.
In case, there will be an official influx2 addon i will abandone my repository - so in that case you have to migrate your data to the official database than.
