### ISSUE TITLE
Typo in config in readme

### ISSUE THREAD

**Issue by timmost** [Dattel/homeassistant-influxdb2#7]
Hi There, 

thansk for the pugin, there seems to be a typo in your configuration examples:
is:                 veryify_ssl: false
should be:   verify_ssl: false

best Timmo

Full config:
#InfluxDB2
influxdb:
  host: localhost
  port: 8087
  api_version: 2
  max_retries: 3
  default_measurement: state
  token: !secret influx_apiToken
  organization: !secret influx_orgID
  bucket: home_assistant
  ssl: false
  **veryify_ssl: false**
  ignore_attributes:
    - device_class
    - device_type
    - icon
    - source
    - state_class
    - status
    - child_lock
    - linkquality
    - update_str
    - update_available
    - indicator_mode
    - voltage
    - power
    - power_outage_memory
    - latest_version
    - installed_version
    - update
    - power_outage_memory
    - energy
    - current
    - battery
    - humidity
    - temperature
  include:
    entities:
      - sensor.rf433_temp_garten
      - sensor.RF433_temp_pool
      - sensor.stromzaehler_powerconsumption

**Comment by Dattel** [comment]
Thanks for pointing out... is there currently any situation, where you have trouble with these setting? 
Otherwise i will correct that in the next days..

**Comment by timmost** [comment]
Hi there,

No, found and fixed it. It hindered home assistant to start, but after
reboot clearly indicated the error. So no prob for me anymore, maybe for
others… but they can see the issue report.

Still working on the influx data capture, as I am still learning Hass ( I
know influx reasonably good from my other installation..
Thx again!


Dattel ***@***.***> schrieb am Mi. 2. Okt. 2024 um 18:03:
