### ISSUE TITLE
Export / Import

### ISSUE THREAD

**Issue by snzyeee** [Dattel/homeassistant-influxdb2#8]
Hey. Thanks for the integration. 

I installed the Add-On as described. Then exported my v1 db wich was insanely big ( 86GB ) and now i try to import it to v2. 

How long did it take for you to import your file? Iam now waiting for 1h and so far i couldnt see anything happen. In log there's only following cursor: 

![image](https://github.com/user-attachments/assets/e9089731-4090-4e9d-aa67-32f771487bd7)

**Comment by Dattel** [comment]
Hi @snzyeee... 
insane :-D.... my dump was about 2GB and the import took only a few minutes.. 
That's an amount of data which could lead to a timeout i think... mayby you are able to split the file so multiple smaller files?

**Comment by snzyeee** [comment]
am i gonna notice the timeout somehow? Cuz theres nothing telling me whats going on. :x

well, can u split it? how to do it? 

i let it run until this evening and cancelled after. 

tried to sort out stuff i dont need and was able to shrink it to 83... WOW. 

i will leave it running now until i see something.

EDIT: 

I just had succes. I started it yesterday evening and it finished to 11am today. 

To be more clear if the process is still running i increased the log level and checked for traffic there from time to time. 
Worked out pretty good.
